run_name: olmoe17-8x1b-rocm-smoketest
seed: 6198
dry_run: false
no_pre_train_checkpoint: true

wandb: null  # disable wandb for smoke test

model:
  d_model: 2048
  n_heads: 16
  n_layers: 8
  mlp_ratio: 8
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_cutoff_factor: 3
  moe_top_k: 2
  moe_num_experts: 8
  moe_dropless: true
  moe_mlp_impl: sparse
  moe_zloss_weight: 0.001
  moe_loss_weight: 0.0
  moe_router_ema_normalize: true
  moe_log_expert_assignment: true

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 1

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 10485760000
  t_max: 3e12
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: /home/morg/students/sagiahrac/repos/olmo-rocm/runs/${run_name}
save_overwrite: true

save_interval: 100
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 1
sharded_checkpointer: olmo_core

load_path: null

max_duration: 1ep
stop_at: 20  # stop after 20 steps — just enough to validate env
global_train_batch_size: 8
device_train_microbatch_size: 4

precision: amp_bf16
activation_checkpointing: fine_grained
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 1000
eval_subset_num_batches: 10
device_eval_batch_size: 4

data:
  num_workers: 4
  drop_last: true
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0
  instance_filter:
      repetition_max_period: 13
      repetition_min_period: 1
      repetition_max_count: 32
  paths:
    - /home/morg/students/sagiahrac/dataset/olmoe-1pct/tokenized/dclm/part-00-00000.npy
    - /home/morg/students/sagiahrac/dataset/olmoe-1pct/tokenized/dclm/part-01-00000.npy
    - /home/morg/students/sagiahrac/dataset/olmoe-1pct/tokenized/dclm/part-02-00000.npy
